import type { NextPage } from 'next';
import Head from 'next/head';
import { ISearchAnime } from '../../model';

import styles from '../../styles/SearchPage.module.scss';
import { GetServerSideProps } from 'next';

import ResultCard from '../../components/ResultCard';
import AnimeGrid from '../../components/AnimeGrid';

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
	const { searchQuery } = query;

	const res = await fetch(`https://api.jikan.moe/v3/search/anime?q=${searchQuery}&page=1`);
	const data = await res.json();

	return {
		props: { data: data.results, searchQuery },
	};
};

interface Props {
	data: ISearchAnime[];
	searchQuery: any;
}

const SearchPage: NextPage<Props> = ({ data, searchQuery }: Props) => {
	// const Home = <T extends Anime>({ topAnime }: Props<T> & { children?: ReactNode }) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<main className={styles.main}>
					<h1>Search Page for "{searchQuery}":</h1>
					<div className={styles.grid}>
						{data &&
							data.map((anime) => {
								return <ResultCard key={anime.mal_id} anime={anime} />;
							})}
					</div>
				</main>
			</div>
		</div>
	);
};

export default SearchPage;
