import Head from 'next/head';
import { useContext } from 'react';
import { AppContext } from '../context/context';
import styles from '../styles/ListPage.module.scss';
import ListCard from '../components/ListCard';

const ListPage = () => {
	const { state } = useContext(AppContext);
	const watchlist = state.watchlist;
	const watched = state.watched;

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h2>Your Watchlist</h2>
				<div className={styles.grid}>
					{watchlist &&
						watchlist.map((anime) => {
							return <ListCard key={anime.mal_id} anime={anime} cardType="watchlistCard" />;
						})}
				</div>
				<h2>Your Watched List</h2>

				<div className={styles.grid}>
					{watched &&
						watched.map((anime) => {
							return <ListCard key={anime.mal_id} anime={anime} cardType="watchedCard" />;
						})}
				</div>
			</main>
		</div>
	);
};

export default ListPage;
