import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import styles from '../styles/SignUpPage.module.scss';
import { useGlobalContext } from '../context/context';

const SignUp = () => {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [confirmPassword, setConfirmPassword] = useState('');
	const [error, setError] = useState(false);
	const { signup } = useGlobalContext();
	const router = useRouter();

	const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		setError(false);

		if (password === confirmPassword) {
			try {
				await signup(email, password);
				setEmail('');
				setPassword('');
				setConfirmPassword('');
				router.push('/');
			} catch (error) {
				console.log(error);
				setError(true);
			}
		}
	};

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<form className={styles.form} onSubmit={(e) => handleSubmit(e)}>
					<h1>Sign Up</h1>
					<div className={styles.inputContainer}>
						<label htmlFor="email">Email</label>
						<input
							type="email"
							placeholder="Enter Email"
							name="email"
							value={email}
							required
							onChange={(e) => setEmail(e.target.value)}
						/>
					</div>
					<div className={styles.inputContainer}>
						<label htmlFor="password">Password</label>
						<input
							type="password"
							placeholder="Enter Password"
							name="password"
							value={password}
							required
							onChange={(e) => setPassword(e.target.value)}
						/>
					</div>
					<div className={styles.inputContainer}>
						<label htmlFor="psw-confirm">Confirm Password</label>
						<input
							type="password"
							placeholder="Repeat Password"
							name="password-confirm"
							value={confirmPassword}
							required
							onChange={(e) => setConfirmPassword(e.target.value)}
						/>
					</div>

					<button>Sign Up</button>
					<p>
						Already have account?{' '}
						<Link href={`/signin`}>
							<span>Sign in</span>
						</Link>
					</p>
					<p>
						Back to{' '}
						<Link href={`/`}>
							<span>Home</span>
						</Link>
					</p>
				</form>
			</main>
		</div>
	);
};

export default SignUp;
