import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

import styles from '../styles/SignInPage.module.scss';
import { useGlobalContext } from '../context/context';

const SignIn = () => {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [error, setError] = useState(false);
	const { login } = useGlobalContext();
	const router = useRouter();

	const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		setError(false);

		try {
			await login(email, password);
			setEmail('');
			setPassword('');
			router.back();
		} catch (error) {
			console.log(error);
			setError(true);
		}
	};

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<form className={styles.form} onSubmit={(e) => handleSubmit(e)}>
					<h1>Sign In</h1>
					<div className={styles.inputContainer}>
						<label htmlFor="email">Email</label>
						<input
							type="email"
							placeholder="Enter Email"
							name="email"
							value={email}
							required
							onChange={(e) => setEmail(e.target.value)}
						/>
					</div>
					<div className={styles.inputContainer}>
						<label htmlFor="password">Password</label>
						<input
							type="password"
							placeholder="Enter Password"
							name="password"
							value={password}
							required
							onChange={(e) => setPassword(e.target.value)}
						/>
					</div>
					{error && <p className={styles.error}>Please input valid email and password</p>}

					<button>Sign Up</button>

					<p>
						Don't have account?
						<Link href={`/signup`}>
							<span>Sign Up</span>
						</Link>
					</p>
					<p>
						Back to
						<Link href={`/`}>
							<span>Home</span>
						</Link>
					</p>
				</form>
			</main>
		</div>
	);
};

export default SignIn;
